# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20171010_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='brand',
            new_name='name',
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
