# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0013_auto_20171011_0449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': '장소', 'verbose_name_plural': '장소 목록'},
        ),
    ]
