# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inheritance', '0005_champion_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Midliner',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('inheritance.champion',),
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('inheritance.champion',),
        ),
        migrations.AlterModelOptions(
            name='champion',
            options={'ordering': ['rank'], 'verbose_name': '챔피언'},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='customer',
        ),
        migrations.AddField(
            model_name='supplier',
            name='supply_places',
            field=models.ManyToManyField(related_name='supply_place_set', related_query_name='supply_query_set', to='inheritance.Place'),
        ),
    ]
